[tool.poetry]
name = "newspaper-crawler"
version = "0.1.0"
description = ""
authors = ["fun <854814501@qq.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
